os: osx
language: swift
osx_image: xcode11.4
xcode_project: Trending Anime.xcodeproj
xcode_scheme: Trending Anime 
xcode_sdk: iphonesimulator13.4
xcode_destination: platform=iOS Simulator,OS=13.4,name=iPhone 11